# Generated by Django 4.1.7 on 2023-03-30 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('condition_out', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], max_length=100)),
                ('condition_in', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Checkouts',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_company', to='Assets.company')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_company', to='Assets.company')),
                ('issued_devices', models.ManyToManyField(related_name='employees_issued_devices', through='Assets.Checkout', to='Assets.device')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='devices',
            field=models.ManyToManyField(editable=False, related_name='company_devices', to='Assets.device'),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(editable=False, related_name='company_employees', to='Assets.employee'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.company'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.device'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.employee'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['name', 'id'], name='Assets_devi_name_50a9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'id'], name='Assets_comp_name_2ca53d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['id'], name='Assets_chec_id_84b034_idx'),
        ),
    ]
